Repository boostcampwm-2021/web18-BooStore, pull requests merged in 2021-11, with the labels that each got.

#2 [Feat] Router 구현, Header 구현
  .gitmessage.txt
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/asset/image/logo.png
  frontend/src/asset/image/profile.png
  frontend/src/component/Header.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Main.tsx
  package-lock.json
  package.json
Labels: 프론트엔드, 기능, 스타일

#3 [Feat] 로그인, 회원가입 레이아웃 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/asset/image/IconLeftArrow.svg
  frontend/src/asset/style/styled.d.ts
  frontend/src/asset/style/theme.ts
  frontend/src/component/LoginComponent.tsx
  frontend/src/component/SignupComponent.tsx
  frontend/src/page/LoginPage.tsx
  frontend/src/page/SignupPage.tsx
Labels: 프론트엔드, 기능, 스타일

#16 [Feat] Mongoose 설치 및 Schema 적용
  backend/bin/www
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/model/cloud.ts
  backend/src/model/index.ts
  backend/src/model/user.ts
  frontend/src/App.tsx
Labels: 세팅, 백엔드

#17 백엔드의 로그인 및 로그아웃, 회원가입 기능 구현
  backend/.env.sample
  backend/.eslintrc.json
  backend/package-lock.json
  backend/package.json
  backend/src/@types/passport.d.ts
  backend/src/app.ts
  backend/src/config/passport.ts
  backend/src/routes/auth.ts
  backend/src/routes/index.ts
  backend/src/service/user.ts
  backend/tsconfig.json
Labels: 백엔드, 기능

#19 프론트엔드 & 백엔드 로그인 기능 연동
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  frontend/.env.sample
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/component/Header.tsx
  frontend/src/component/LoginComponent.tsx
  frontend/src/component/SignupComponent.tsx
  frontend/src/index.tsx
  frontend/src/model/index.ts
  frontend/src/model/user.ts
  frontend/src/page/LoginPage.tsx
Labels: 리팩토링, 백엔드, 프론트엔드, 기능

#20 로그인, 회원가입 유효성 검사 및 모달 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/component/Header.tsx
  frontend/src/component/LoginComponent.tsx
  frontend/src/component/SignupComponent.tsx
  package-lock.json
  package.json
Labels: 프론트엔드, 기능, 스타일

#21 모달창 스타일 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/component/LoginComponent.tsx
  frontend/src/component/SignupComponent.tsx
  package-lock.json
  package.json
Labels: 프론트엔드, 스타일

#22 [Feat] 비밀번호 불일치 경고 추가
  frontend/src/component/SignupComponent.tsx
Labels: 프론트엔드, 기능

#26 [Chore] Docker 파일 작성
  .dockerignore
  Dockerfile
  docker-compose.yml
  frontend/package-lock.json
  nginx.conf
Labels: 백엔드

#27 무중단배포 구현
  .dockerignore
  script/deploy.sh
Labels: 세팅

#34 새로고침시 로그인을 유지하도록 수정함
  backend/package-lock.json
  backend/package.json
  backend/src/DTO/index.ts
  backend/src/DTO/user.ts
  backend/src/app.ts
  backend/src/config/passport.ts
  backend/src/routes/index.ts
  backend/src/routes/user.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/component/LoginComponent.tsx
  frontend/src/component/SignupComponent.tsx
Labels: 리팩토링, 백엔드, 프론트엔드, 기능

#40 object storage 연동 및 업로드 테스트
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/model/.keep
  backend/src/model/object-storage.ts
  backend/src/routes/auth.ts
Labels: 백엔드

#44 사용자의 현재/최대 용량을 수정/조회하는 기능 구현
  backend/src/DTO/capacity.ts
  backend/src/DTO/index.ts
  backend/src/DTO/user.ts
  backend/src/route/auth.ts
  backend/src/route/user.ts
  backend/src/service/cloud/capacity.ts
  backend/src/service/cloud/index.ts
  backend/src/service/index.ts
  frontend/src/model/user.ts
Labels: 백엔드, 기능

#45 Feature/#37
  backend/src/config/.keep
  backend/src/service/.keep
  frontend/src/component/FileMenu.tsx
  frontend/src/component/ModalComponent.tsx
Labels: 프론트엔드, 기능

#46 서버의 파일 업로드 api 구현
  .gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/middleware/index.ts
  backend/src/middleware/multer.ts
  backend/src/middleware/passport.ts
  backend/src/route/auth.ts
  backend/src/route/cloud.ts
  backend/src/route/index.ts
  backend/src/route/user.ts
Labels: 백엔드, 기능

#47 사용자의 현재/최대 사용량 조회 UI 구현
  frontend/src/Router.tsx
  frontend/src/component/Sidebar.tsx
  frontend/src/model/capacity.ts
  frontend/src/model/index.ts
  frontend/src/page/MainPage.tsx
  frontend/src/util/capacity.ts
Labels: 프론트엔드, 기능

#49 [Feat] 파일 메타데이터 MongoDB저장
  backend/src/route/cloud.ts
  backend/src/service/cloud/index.ts
  frontend/src/component/FileMenu.tsx
Labels: 백엔드, 기능

#50 클라이언트 파일 업로드 유효성 검사 추가 및 모달 스타일 수정
  backend/src/route/cloud.ts
  backend/src/service/cloud/capacity.ts
  frontend/src/component/FileMenu.tsx
  frontend/src/component/ModalComponent.tsx
  frontend/src/page/MainPage.tsx
Labels: 프론트엔드, 기능, 스타일

#52 [페어 프로그래밍] 파일, 폴더 업로드 기능 추가
  backend/src/model/cloud.ts
  backend/src/route/cloud.ts
  backend/src/service/cloud/upload.ts
  frontend/src/component/FileMenu.tsx
Labels: 리팩토링, 백엔드, 프론트엔드, 기능

#59 파일을 보낼때 프로그래스 모달을 보여주도록 구현함
  backend/src/service/cloud/upload.ts
  frontend/src/component/FileMenu.tsx
  frontend/src/component/ModalComponent.tsx
  frontend/src/component/ProgressBar.tsx
  frontend/src/component/Sidebar.tsx
Labels: 리팩토링, 프론트엔드, 기능

#66 파일 업로드시 드롭박스 추가
  frontend/src/component/DropBox.tsx
  frontend/src/component/FileMenu.tsx
Labels: 프론트엔드, 기능

#67 페이지 레이아웃 수정
  frontend/src/asset/style/theme.ts
  frontend/src/component/Header.tsx
Labels: 프론트엔드, 스타일

#68 파일 선택 기능 추가
  frontend/src/App.tsx
  frontend/src/DTO/file.ts
  frontend/src/component/Button.tsx
  frontend/src/component/File.tsx
  frontend/src/component/FileList.tsx
  frontend/src/component/FileMenu.tsx
  frontend/src/page/MainPage.tsx
Labels: 프론트엔드, 기능, 스타일

#70 로그아웃 기능 구현
  frontend/src/App.tsx
  frontend/src/asset/style/theme.ts
  frontend/src/component/Header.tsx
Labels: 프론트엔드, 기능

#73 [Style] folder hover 코드 변경
  frontend/src/component/File.tsx
Labels: 스타일

#75 로그아웃 버튼 레이아웃 변경
  frontend/src/component/Header.tsx
Labels: 프론트엔드, 스타일

#90 디렉토리 별 클릭 이벤트 추가
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo.svg
  frontend/src/asset/image/logo.png
  frontend/src/asset/style/global-styles.ts
  frontend/src/asset/style/theme.ts
  frontend/src/component/fileManagement/File.tsx
  frontend/src/component/layout/Header.tsx
  frontend/src/page/MainPage.tsx
Labels: 프론트엔드, 기능

#91 디자인 및 기능 수정
  backend/src/route/user.ts
  backend/src/service/cloud/directory.ts
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo.svg
  frontend/src/App.tsx
  frontend/src/asset/css/font.css
  frontend/src/asset/image/icons/icon_login_password.svg
  frontend/src/asset/image/icons/icon_login_user.svg
  frontend/src/asset/image/logo.png
  frontend/src/asset/style/global-styles.ts
  frontend/src/asset/style/styled.d.ts
  frontend/src/asset/style/theme.ts
  frontend/src/component/DirectoryList/Directory.tsx
  frontend/src/component/DirectoryList/DirectoryList.tsx
  frontend/src/component/DirectoryList/index.ts
  frontend/src/component/LoginComponent.tsx
  frontend/src/component/SignupComponent.tsx
  frontend/src/component/common/Button.tsx
  frontend/src/component/common/DropBox.tsx
  frontend/src/component/common/Input.tsx
  frontend/src/component/common/ModalComponent.tsx
  frontend/src/component/common/ModalComponent/Modal.tsx
  frontend/src/component/common/ModalComponent/ModalIcon.tsx
  frontend/src/component/common/ModalComponent/index.ts
  frontend/src/component/common/ModalComponent/type.ts
  frontend/src/component/common/ProgressBar.tsx
  frontend/src/component/fileManagement/File.tsx
  frontend/src/component/fileManagement/FileIcon.tsx
  frontend/src/component/fileManagement/FileList.tsx
  frontend/src/component/fileManagement/FileMenu.tsx
  frontend/src/component/fileManagement/TypeIcon.tsx
  frontend/src/component/layout/Header.tsx
  frontend/src/component/layout/Sidebar.tsx
  frontend/src/page/MainPage.tsx
  frontend/src/util/capacity.ts
  frontend/src/util/file.ts
Labels: 리팩토링, 백엔드, 프론트엔드, 기능

#97 파일 리스트 요청 API 및 파일 아이콘 오류 수정
  backend/src/service/cloud/directory.ts
  frontend/src/component/fileManagement/FileIcon.tsx
Labels: 백엔드, 스타일

#100 파일 다운로드 api 구현 중
  backend/src/route/cloud.ts
  backend/src/service/cloud/download.ts
  backend/src/service/cloud/index.ts
Labels: 백엔드, 프론트엔드, 기능

#103 사이드바 디렉토리 구조 구현
  backend/src/route/cloud.ts
  backend/src/route/user.ts
  backend/src/service/cloud/directory.ts
  frontend/src/api/getDirectory.ts
  frontend/src/api/index.ts
  frontend/src/component/DirectoryList/DirectoryList.tsx
  frontend/src/component/layout/Sidebar.tsx
  frontend/src/page/MainPage.tsx
  frontend/src/page/TrashPage.tsx
  frontend/src/util/index.ts
  frontend/src/util/tree.ts
  frontend/tsconfig.path.json
Labels: 백엔드, 프론트엔드, 기능

#104 [Refactor] 로그인, 회원가입 모달창 변경
  frontend/src/component/LoginComponent.tsx
  frontend/src/component/SignupComponent.tsx
  frontend/src/page/LoginPage.tsx
  frontend/src/page/SignupPage.tsx
Labels: 리팩토링, 스타일

#105 파일 다운로드 기능 추가
  backend/package-lock.json
  backend/package.json
  backend/src/route/cloud.ts
  backend/src/service/cloud/download.ts
  frontend/src/component/fileManagement/FileMenuForMain.tsx
Labels: 백엔드, 프론트엔드, 기능

#106 세션스토리지로 mogodb를 사용하도록 함
  backend/.env.sample
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
Labels: 백엔드, 기능

#107 드래그 & 셀렉트 구현
  backend/.env.sample
  backend/src/service/cloud/directory.ts
  backend/src/service/user.ts
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/component/common/ModalComponent/Modal.tsx
  frontend/src/component/fileManagement/File.tsx
  frontend/src/component/fileManagement/FileList.tsx
  frontend/src/component/fileManagement/FileMenuForMain.tsx
  frontend/src/component/fileManagement/FileMenuForTrash.tsx
  frontend/src/component/fileManagement/Selection.tsx
  frontend/src/component/layout/Header.tsx
  frontend/src/page/MainPage.tsx
  frontend/src/page/TrashPage.tsx
Labels: 프론트엔드, 기능, 스타일

#110 사이드바 디렉토리 리스트의 네비게이션이 정상작동하도록 수정
  frontend/src/component/DirectoryList/DirectoryList.tsx
  frontend/src/page/MainPage.tsx
Labels: 버그, 프론트엔드

#111 버그 수정
  backend/src/route/cloud.ts
  backend/src/service/cloud/download.ts
Labels: 버그, 백엔드

#112 [Fix] 파일이 정상적으로 다운로드 되지 않는 문제 수정
  backend/src/route/cloud.ts
  backend/src/service/cloud/download.ts
Labels: 버그

#114 CI/CD 스크립트 적용
  .github/workflows/Deploy.yaml
  .github/workflows/Testing.yaml
  backend/.eslintrc.json
  backend/package.json
  backend/src/DTO/capacity.ts
  backend/src/DTO/cloud.ts
  backend/src/DTO/index.ts
  backend/src/DTO/user.ts
  backend/src/app.ts
  backend/src/config/nodeSchedule.ts
  backend/src/config/passport.ts
  backend/src/middleware/index.ts
  backend/src/middleware/multer.ts
  backend/src/middleware/passport.ts
  backend/src/model/cloud.ts
  backend/src/model/object-storage.ts
  backend/src/model/user.ts
  backend/src/route/auth.ts
  backend/src/route/cloud.ts
  backend/src/route/user.ts
  backend/src/service/cloud/capacity.ts
  backend/src/service/cloud/directory.ts
  backend/src/service/cloud/download.ts
  backend/src/service/cloud/file.ts
  backend/src/service/index.ts
  backend/src/service/user.ts
  frontend/src/model/user.ts
  script/build.sh
  script/lint.sh
  script/tsc.sh
Labels: 세팅

#122 파일의 올린 날짜/수정 날짜가 맞지 않던 버그를 수정함
  frontend/src/util/date.ts
Labels: 프론트엔드

#123 파일 업로드의 비동기 로직 수정
  backend/src/route/cloud.ts
Labels: 리팩토링, 백엔드

#126 파일 업로드시, 디렉토리도 도큐먼트를 만들도록 구현함
  backend/src/model/cloud.ts
  backend/src/service/cloud/file.ts
Labels: 백엔드, 기능

#128 스크롤 시, 드래그 박스가 따라오지 않는 버그를 수정함
  frontend/src/component/fileManagement/FileList.tsx
  frontend/src/component/fileManagement/Selection.tsx
Labels: 버그, 프론트엔드

#129 성능 개선을 위한 리팩토링 진행
  frontend/src/component/fileManagement/File.tsx
  frontend/src/component/fileManagement/FileList.tsx
  frontend/src/component/fileManagement/FileMenuForMain.tsx
  frontend/src/component/fileManagement/FileMenuForTrash.tsx
  frontend/src/component/fileManagement/Selection.tsx
  frontend/src/page/MainPage.tsx
  frontend/src/page/TrashPage.tsx
  frontend/src/util/throttle.ts
Labels: 리팩토링, 프론트엔드

#130 [Refactor] 변경된 요구사항에 맞게 다운로드 API 수정
  backend/src/service/cloud/download.ts
Labels: 리팩토링, 백엔드

#131 [Refactor] 특정 디렉토리의 리스트를 불러오는 API 수정
  backend/src/service/cloud/directory.ts
Labels: 리팩토링, 백엔드

#134 Feature/#116
  backend/src/route/cloud.ts
  backend/src/route/user.ts
  backend/src/service/cloud/directory.ts
  backend/src/service/cloud/file.ts
  frontend/src/App.tsx
  frontend/src/component/DirectoryList/DirectoryList.tsx
  frontend/src/component/HeaderContextMenu.tsx
  frontend/src/component/common/ContextDropdown.tsx
  frontend/src/component/fileManagement/FileList.tsx
  frontend/src/component/fileManagement/NewFolderModal.tsx
  frontend/src/component/hook/useContextMenu.ts
  frontend/src/component/layout/Sidebar.tsx
  frontend/src/page/MainPage.tsx
  frontend/src/page/TrashPage.tsx
  frontend/src/util/tree.ts
Labels: 백엔드, 프론트엔드, 기능

#135 설계 변경에 따른 파일 삭제 및 업로드 로직 수정
  backend/src/route/cloud.ts
  backend/src/route/user.ts
  backend/src/service/cloud/directory.ts
  backend/src/service/cloud/file.ts
  backend/src/util/index.ts
  backend/src/util/regex.ts
  frontend/src/api/file.ts
  frontend/src/api/getTrashFiles.ts
  frontend/src/api/index.ts
  frontend/src/component/DirectoryList/DirectoryList.tsx
  frontend/src/component/HeaderContextMenu.tsx
  frontend/src/component/fileManagement/File.tsx
  frontend/src/component/fileManagement/FileList.tsx
  frontend/src/component/fileManagement/FileMenuForMain.tsx
  frontend/src/component/fileManagement/FileMenuForTrash.tsx
  frontend/src/component/fileManagement/NewFolderModal.tsx
  frontend/src/component/fileManagement/Selection.tsx
  frontend/src/page/TrashPage.tsx
  frontend/src/util/tree.ts
Labels: 버그, 리팩토링, 백엔드, 프론트엔드, 기능

#136 드래그 박스가 파일리스트의 헤더위로 올라가는 버그를 수정
  frontend/src/component/common/DropBox.tsx
  frontend/src/component/fileManagement/FileList.tsx
  frontend/src/component/fileManagement/Selection.tsx
  frontend/src/component/layout/Header.tsx
Labels: 프론트엔드, 스타일

#137 새 폴더 만들기 기능 구현 완료
  backend/src/route/cloud.ts
  backend/src/service/cloud/directory.ts
  frontend/src/api/index.ts
  frontend/src/api/newFolder.ts
  frontend/src/component/common/ContextDropdown.tsx
  frontend/src/component/fileManagement/FileList.tsx
  frontend/src/component/fileManagement/NewFolderModal.tsx
  frontend/src/component/hook/useContextMenu.ts
Labels: 백엔드, 프론트엔드, 기능

#139 [Fix] 다운로드 API 수정
  backend/src/route/cloud.ts
  backend/src/service/cloud/download.ts
  frontend/src/component/hook/useContextMenu.ts
Labels: 버그, 백엔드

#141 Feature/#96
  backend/src/route/cloud.ts
  backend/src/service/cloud/file.ts
  frontend/src/api/getDirectory.ts
  frontend/src/api/index.ts
  frontend/src/api/moveFile.ts
  frontend/src/api/newFolder.ts
  frontend/src/component/common/ContextDropdown.tsx
  frontend/src/component/common/ContextMenu.tsx
  frontend/src/component/fileManagement/FileList.tsx
  frontend/src/component/fileManagement/FileListForStar.tsx
  frontend/src/component/fileManagement/MoveFileModal.tsx
  frontend/src/component/hook/useContextMenu.ts
  frontend/src/page/MainPage.tsx
Labels: 백엔드, 프론트엔드, 기능

#145 대략적인 스타일 수정
  backend/src/route/cloud.ts
  backend/src/service/cloud/file.ts
  frontend/src/asset/style/global-styles.ts
  frontend/src/component/common/ContextDropdown.tsx
  frontend/src/component/common/ContextMenu.tsx
  frontend/src/component/fileManagement/MoveFileModal.tsx
  frontend/src/page/MainPage.tsx
Labels: 프론트엔드, 스타일

#147 UI 수정 및 UX 개선
  frontend/src/component/LoginComponent.tsx
  frontend/src/component/SignupComponent.tsx
  frontend/src/component/fileManagement/NewFolderModal.tsx
  frontend/src/component/layout/Sidebar.tsx
  frontend/src/page/MainPage.tsx
  frontend/src/page/StarPage.tsx
  frontend/src/page/TrashPage.tsx
Labels: 프론트엔드, 기능, 스타일

#148 중복된 이름으로 새 폴더 생성 방지 기능 구현
  frontend/src/component/fileManagement/FileMenuForMain.tsx
  frontend/src/component/fileManagement/NewFolderModal.tsx
  frontend/src/util/file.ts
Labels: 프론트엔드, 기능

#150 폴더 경로 이동 구현
  backend/src/DTO/cloud.ts
  backend/src/route/cloud.ts
  backend/src/service/cloud/file.ts
  backend/src/service/cloud/index.ts
  backend/src/service/cloud/update.ts
  frontend/src/api/moveFile.ts
  frontend/src/component/fileManagement/FileMenuForMain.tsx
  frontend/src/component/fileManagement/FileMenuForStar.tsx
  frontend/src/component/fileManagement/FileMenuForTrash.tsx
  frontend/src/component/fileManagement/MoveFileModal.tsx
  frontend/src/util/index.ts
  frontend/src/util/regex.ts
Labels: 백엔드, 프론트엔드, 기능

#151 로그아웃 모달 레이아웃 수정
  frontend/src/component/layout/Header.tsx
Labels: 프론트엔드, 스타일

#153 백엔드 서버의 보안 강화
  backend/src/route/cloud.ts
Labels: 버그, 백엔드

#154 [Fix] 백엔드 서버의 보안 강화
  backend/src/route/cloud.ts
Labels: 버그, 백엔드

#156 [Refactor] 백엔드 리팩토링
  backend/src/route/cloud.ts
  backend/src/route/user.ts
  frontend/src/util/file.ts
Labels: 리팩토링, 백엔드

#157 [J010] 백엔드 리팩토링, contextmenu 스타일 변경
  backend/src/route/cloud.ts
  frontend/src/api/cloud.ts
  frontend/src/api/moveFile.ts
  frontend/src/component/common/ContextMenu.tsx
  frontend/src/component/fileManagement/File.tsx
  frontend/src/component/fileManagement/FileForStar.tsx
  frontend/src/page/MainPage.tsx
Labels: 리팩토링, 백엔드, 스타일

#158 백엔드 영역 리팩토링 작업
  backend/.env.sample
  backend/src/route/cloud.ts
  backend/src/service/cloud/capacity.ts
  backend/src/service/cloud/file.ts
  backend/src/service/cloud/update.ts
Labels: 리팩토링, 백엔드

#159 백엔드 리팩토링 작업 dev에 반영
  backend/.env.sample
  backend/src/route/cloud.ts
  backend/src/route/user.ts
  backend/src/service/cloud/capacity.ts
  backend/src/service/cloud/file.ts
  backend/src/service/cloud/update.ts
  frontend/src/api/cloud.ts
  frontend/src/api/moveFile.ts
  frontend/src/component/common/ContextMenu.tsx
  frontend/src/component/fileManagement/File.tsx
  frontend/src/component/fileManagement/FileForStar.tsx
  frontend/src/page/MainPage.tsx
  frontend/src/util/file.ts
Labels: 리팩토링, 백엔드

#162 프론트엔드 리팩토링
  frontend/src/component/LoginComponent.tsx
  frontend/src/component/SignupComponent.tsx
  frontend/src/component/common/ContextMenu.tsx
  frontend/src/component/fileManagement/File.tsx
  frontend/src/page/LoginPage.tsx
  frontend/src/page/SignupPage.tsx
Labels: 리팩토링, 프론트엔드

#163 프론트엔드 Fetch API를 함수로 모듈화함
  backend/src/route/cloud.ts
  frontend/src/api/capacity.ts
  frontend/src/api/cloud.ts
  frontend/src/api/getTrashFiles.ts
  frontend/src/api/handleTrashFiles.ts
  frontend/src/api/index.ts
  frontend/src/api/moveFile.ts
  frontend/src/component/common/ContextMenu.tsx
Labels: 리팩토링, 프론트엔드

#164 프론트엔드 리팩토링 작업
  frontend/src/api/capacity.ts
  frontend/src/component/common/modalComponent/Modal.tsx
  frontend/src/component/common/modalComponent/ModalIcon.tsx
  frontend/src/component/common/modalComponent/index.ts
  frontend/src/component/common/modalComponent/type.ts
  frontend/src/component/directoryList/Directory.tsx
  frontend/src/component/directoryList/DirectoryList.tsx
  frontend/src/component/directoryList/index.ts
  frontend/src/component/fileManagement/FileForStar.tsx
  frontend/src/component/fileManagement/FileMenuForMain.tsx
  frontend/src/component/fileManagement/FileMenuForStar.tsx
  frontend/src/component/fileManagement/FileMenuForTrash.tsx
  frontend/src/component/fileManagement/NewFolderModal.tsx
  frontend/src/component/layout/Sidebar.tsx
  frontend/src/page/LoginPage.tsx
  frontend/src/page/SignupPage.tsx
Labels: 리팩토링, 프론트엔드

#165 다운로드 관련 함수 리팩토링
  backend/.env.sample
  frontend/src/api/cloud.ts
  frontend/src/api/download.ts
  frontend/src/api/index.ts
  frontend/src/component/common/ContextMenu.tsx
  frontend/src/component/fileManagement/FileMenuForMain.tsx
  frontend/src/component/fileManagement/FileMenuForStar.tsx
Labels: 버그, 리팩토링, 프론트엔드

#166 프론트엔드 영역 코드 리팩토링 진행 중
  backend/.env.sample
  backend/src/route/cloud.ts
  frontend/src/api/moveFile.ts
  frontend/src/component/common/ContextMenu.tsx
  frontend/src/component/common/Input.tsx
  frontend/src/component/common/ProgressBar.tsx
  frontend/src/component/common/modalComponent/ModalIcon.tsx
  frontend/src/component/directoryList/DirectoryList.tsx
  frontend/src/component/fileManagement/File.tsx
  frontend/src/component/fileManagement/FileForStar.tsx
  frontend/src/component/fileManagement/FileIcon.tsx
  frontend/src/component/fileManagement/FileList.tsx
  frontend/src/component/fileManagement/FileListForStar.tsx
  frontend/src/component/fileManagement/FileMenuForMain.tsx
  frontend/src/component/fileManagement/FileMenuForStar.tsx
  frontend/src/component/fileManagement/FileMenuForTrash.tsx
  frontend/src/component/fileManagement/NewFolderModal.tsx
  frontend/src/component/fileManagement/Selection.tsx
  frontend/src/component/layout/Sidebar.tsx
  frontend/src/page/MainPage.tsx
  frontend/src/page/StarPage.tsx
  frontend/src/page/TrashPage.tsx
  frontend/src/util/file.ts
Labels: 리팩토링, 프론트엔드

#168 프론트엔드 리팩토링 진행
  backend/src/config/nodeSchedule.ts
  backend/src/route/cloud.ts
  frontend/src/api/capacity.ts
  frontend/src/api/cloud.ts
  frontend/src/api/download.ts
  frontend/src/api/getTrashFiles.ts
  frontend/src/api/handleTrashFiles.ts
  frontend/src/api/index.ts
  frontend/src/api/moveFile.ts
  frontend/src/component/LoginComponent.tsx
  frontend/src/component/SignupComponent.tsx
  frontend/src/component/common/ContextMenu.tsx
  frontend/src/component/common/Input.tsx
  frontend/src/component/common/ProgressBar.tsx
  frontend/src/component/common/modalComponent/Modal.tsx
  frontend/src/component/common/modalComponent/ModalIcon.tsx
  frontend/src/component/common/modalComponent/index.ts
  frontend/src/component/common/modalComponent/type.ts
  frontend/src/component/directoryList/Directory.tsx
  frontend/src/component/directoryList/DirectoryList.tsx
  frontend/src/component/directoryList/index.ts
  frontend/src/component/fileManagement/File.tsx
  frontend/src/component/fileManagement/FileForStar.tsx
  frontend/src/component/fileManagement/FileIcon.tsx
  frontend/src/component/fileManagement/FileList.tsx
  frontend/src/component/fileManagement/FileListForStar.tsx
  frontend/src/component/fileManagement/FileMenuForMain.tsx
  frontend/src/component/fileManagement/FileMenuForStar.tsx
  frontend/src/component/fileManagement/FileMenuForTrash.tsx
  frontend/src/component/fileManagement/NewFolderModal.tsx
  frontend/src/component/fileManagement/Selection.tsx
  frontend/src/component/layout/Sidebar.tsx
  frontend/src/page/LoginPage.tsx
  frontend/src/page/MainPage.tsx
  frontend/src/page/SignupPage.tsx
  frontend/src/page/StarPage.tsx
  frontend/src/page/TrashPage.tsx
  frontend/src/util/file.ts
Labels: 리팩토링, 프론트엔드

#169 폴더를 빠르게 클릭할 시, 경로가 꼬이는 버그를 수정함
  frontend/src/component/fileManagement/File.tsx
Labels: 버그, 프론트엔드
